#[derive(Clone, PartialEq)]
pub struct RedisCommand {
    pub name: &'static str,
    pub syntax: &'static str,
    pub description: &'static str,
    pub group: &'static str,
}

pub const REDIS_COMMANDS: &[RedisCommand] = &[
    RedisCommand { name: "SET", syntax: "SET key value [NX|XX] [GET] [EX seconds|PX milliseconds|EXAT unix-time-seconds|PXAT unix-time-milliseconds|KEEPTTL]", description: "Set key to hold the string value", group: "string" },
    RedisCommand { name: "GET", syntax: "GET key", description: "Get the value of a key", group: "string" },
    RedisCommand { name: "DEL", syntax: "DEL key [key ...]", description: "Delete a key", group: "generic" },
    RedisCommand { name: "EXISTS", syntax: "EXISTS key [key ...]", description: "Determine if a key exists", group: "generic" },
    RedisCommand { name: "EXPIRE", syntax: "EXPIRE key seconds [NX|XX|GT|LT]", description: "Set a key's time to live in seconds", group: "generic" },
    RedisCommand { name: "TTL", syntax: "TTL key", description: "Get the time to live for a key in seconds", group: "generic" },
    RedisCommand { name: "PERSIST", syntax: "PERSIST key", description: "Remove the expiration from a key", group: "generic" },
    RedisCommand { name: "KEYS", syntax: "KEYS pattern", description: "Find all keys matching the given pattern", group: "generic" },
    RedisCommand { name: "SCAN", syntax: "SCAN cursor [MATCH pattern] [COUNT count] [TYPE type]", description: "Incrementally iterate the keys space", group: "generic" },
    RedisCommand { name: "TYPE", syntax: "TYPE key", description: "Determine the type stored at key", group: "generic" },
    RedisCommand { name: "RENAME", syntax: "RENAME key newkey", description: "Rename a key", group: "generic" },
    RedisCommand { name: "HSET", syntax: "HSET key field value [field value ...]", description: "Set the string value of a hash field", group: "hash" },
    RedisCommand { name: "HGET", syntax: "HGET key field", description: "Get the value of a hash field", group: "hash" },
    RedisCommand { name: "HGETALL", syntax: "HGETALL key", description: "Get all the fields and values in a hash", group: "hash" },
    RedisCommand { name: "HDEL", syntax: "HDEL key field [field ...]", description: "Delete one or more hash fields", group: "hash" },
    RedisCommand { name: "HEXISTS", syntax: "HEXISTS key field", description: "Determine if a hash field exists", group: "hash" },
    RedisCommand { name: "HKEYS", syntax: "HKEYS key", description: "Get all the fields in a hash", group: "hash" },
    RedisCommand { name: "HLEN", syntax: "HLEN key", description: "Get the number of fields in a hash", group: "hash" },
    RedisCommand { name: "LPUSH", syntax: "LPUSH key element [element ...]", description: "Prepend one or more elements to a list", group: "list" },
    RedisCommand { name: "RPUSH", syntax: "RPUSH key element [element ...]", description: "Append one or more elements to a list", group: "list" },
    RedisCommand { name: "LPOP", syntax: "LPOP key [count]", description: "Remove and get the first elements in a list", group: "list" },
    RedisCommand { name: "RPOP", syntax: "RPOP key [count]", description: "Remove and get the last elements in a list", group: "list" },
    RedisCommand { name: "LRANGE", syntax: "LRANGE key start stop", description: "Get a range of elements from a list", group: "list" },
    RedisCommand { name: "LLEN", syntax: "LLEN key", description: "Get the length of a list", group: "list" },
    RedisCommand { name: "LINDEX", syntax: "LINDEX key index", description: "Get an element from a list by its index", group: "list" },
    RedisCommand { name: "LSET", syntax: "LSET key index element", description: "Set the value of an element in a list by its index", group: "list" },
    RedisCommand { name: "SADD", syntax: "SADD key member [member ...]", description: "Add one or more members to a set", group: "set" },
    RedisCommand { name: "SREM", syntax: "SREM key member [member ...]", description: "Remove one or more members from a set", group: "set" },
    RedisCommand { name: "SMEMBERS", syntax: "SMEMBERS key", description: "Get all the members in a set", group: "set" },
    RedisCommand { name: "SISMEMBER", syntax: "SISMEMBER key member", description: "Determine if a given value is a member of a set", group: "set" },
    RedisCommand { name: "SCARD", syntax: "SCARD key", description: "Get the number of members in a set", group: "set" },
    RedisCommand { name: "ZADD", syntax: "ZADD key [NX|XX] [GT|LT] [CH] [INCR] score member [score member ...]", description: "Add one or more members to a sorted set", group: "sorted_set" },
    RedisCommand { name: "ZREM", syntax: "ZREM key member [member ...]", description: "Remove one or more members from a sorted set", group: "sorted_set" },
    RedisCommand { name: "ZRANGE", syntax: "ZRANGE key start stop [BYSCORE | BYLEX] [REV] [LIMIT offset count] [WITHSCORES]", description: "Return a range of members in a sorted set", group: "sorted_set" },
    RedisCommand { name: "ZCARD", syntax: "ZCARD key", description: "Get the number of members in a sorted set", group: "sorted_set" },
    RedisCommand { name: "ZSCORE", syntax: "ZSCORE key member", description: "Get the score associated with the given member in a sorted set", group: "sorted_set" },
    RedisCommand { name: "XADD", syntax: "XADD key [NOMKSTREAM] [<MAXLEN|MINID> [=|~] threshold [LIMIT count]] *|ID field value [field value ...]", description: "Append a new entry to a stream", group: "stream" },
    RedisCommand { name: "XRANGE", syntax: "XRANGE key start end [COUNT count]", description: "Return a range of elements in a stream", group: "stream" },
    RedisCommand { name: "XLEN", syntax: "XLEN key", description: "Return the number of entries in a stream", group: "stream" },
    RedisCommand { name: "XDEL", syntax: "XDEL key ID [ID ...]", description: "Remove the specified entries from the stream", group: "stream" },
    RedisCommand { name: "INFO", syntax: "INFO [section [section ...]]", description: "Get information and statistics about the server", group: "server" },
    RedisCommand { name: "DBSIZE", syntax: "DBSIZE", description: "Return the number of keys in the selected database", group: "server" },
    RedisCommand { name: "FLUSHDB", syntax: "FLUSHDB [ASYNC|SYNC]", description: "Remove all keys from the current database", group: "server" },
    RedisCommand { name: "FLUSHALL", syntax: "FLUSHALL [ASYNC|SYNC]", description: "Remove all keys from all databases", group: "server" },
    RedisCommand { name: "CLIENT", syntax: "CLIENT subcommand [arguments]", description: "A container for client connection commands", group: "server" },
    RedisCommand { name: "SLOWLOG", syntax: "SLOWLOG subcommand [argument]", description: "Manages the Redis slow queries log", group: "server" },
    RedisCommand { name: "CONFIG", syntax: "CONFIG subcommand [argument]", description: "Configure Redis server parameters", group: "server" },
    RedisCommand { name: "PING", syntax: "PING [message]", description: "Ping the server", group: "connection" },
    RedisCommand { name: "ECHO", syntax: "ECHO message", description: "Echo the given string", group: "connection" },
    RedisCommand { name: "SELECT", syntax: "SELECT index", description: "Change the selected database for the current connection", group: "connection" },
    RedisCommand { name: "AUTH", syntax: "AUTH [username] password", description: "Authenticate to the server", group: "connection" },
    RedisCommand { name: "QUIT", syntax: "QUIT", description: "Close the connection", group: "connection" },
    RedisCommand { name: "MULTI", syntax: "MULTI", description: "Mark the start of a transaction block", group: "transactions" },
    RedisCommand { name: "EXEC", syntax: "EXEC", description: "Execute all commands issued after MULTI", group: "transactions" },
    RedisCommand { name: "DISCARD", syntax: "DISCARD", description: "Discard all commands issued after MULTI", group: "transactions" },
    RedisCommand { name: "WATCH", syntax: "WATCH key [key ...]", description: "Watch the given keys to determine execution of the MULTI/EXEC block", group: "transactions" },
    RedisCommand { name: "UNWATCH", syntax: "UNWATCH", description: "Forget about all watched keys", group: "transactions" },
    RedisCommand { name: "INCR", syntax: "INCR key", description: "Increment the integer value of a key by one", group: "string" },
    RedisCommand { name: "DECR", syntax: "DECR key", description: "Decrement the integer value of a key by one", group: "string" },
    RedisCommand { name: "INCRBY", syntax: "INCRBY key increment", description: "Increment the integer value of a key by the given amount", group: "string" },
    RedisCommand { name: "APPEND", syntax: "APPEND key value", description: "Append a value to a key", group: "string" },
    RedisCommand { name: "STRLEN", syntax: "STRLEN key", description: "Get the length of the value stored in a key", group: "string" },
    RedisCommand { name: "MGET", syntax: "MGET key [key ...]", description: "Get the values of all the given keys", group: "string" },
    RedisCommand { name: "MSET", syntax: "MSET key value [key value ...]", description: "Set multiple keys to multiple values", group: "string" },
    RedisCommand { name: "SETEX", syntax: "SETEX key seconds value", description: "Set key to hold the string value and set expiration", group: "string" },
    RedisCommand { name: "SETNX", syntax: "SETNX key value", description: "Set key to hold string value if key does not exist", group: "string" },
    RedisCommand { name: "GETSET", syntax: "GETSET key value", description: "Set the string value of a key and return its old value", group: "string" },
    RedisCommand { name: "GETRANGE", syntax: "GETRANGE key start end", description: "Get a substring of the string stored at a key", group: "string" },
    RedisCommand { name: "SETRANGE", syntax: "SETRANGE key offset value", description: "Overwrite part of a string at key starting at the specified offset", group: "string" },
    RedisCommand { name: "HSETNX", syntax: "HSETNX key field value", description: "Set the value of a hash field, only if the field does not exist", group: "hash" },
    RedisCommand { name: "HMSET", syntax: "HMSET key field value [field value ...]", description: "Set multiple hash fields to multiple values", group: "hash" },
    RedisCommand { name: "HMGET", syntax: "HMGET key field [field ...]", description: "Get the values of all the given hash fields", group: "hash" },
    RedisCommand { name: "HINCRBY", syntax: "HINCRBY key field increment", description: "Increment the integer value of a hash field by the given number", group: "hash" },
    RedisCommand { name: "HINCRBYFLOAT", syntax: "HINCRBYFLOAT key field increment", description: "Increment the float value of a hash field by the given amount", group: "hash" },
    RedisCommand { name: "HVALS", syntax: "HVALS key", description: "Get all the values in a hash", group: "hash" },
    RedisCommand { name: "HSTRLEN", syntax: "HSTRLEN key field", description: "Get the length of the value of a hash field", group: "hash" },
    RedisCommand { name: "LINSERT", syntax: "LINSERT key BEFORE|AFTER pivot element", description: "Insert an element before or after another element in a list", group: "list" },
    RedisCommand { name: "LREM", syntax: "LREM key count element", description: "Remove elements from a list", group: "list" },
    RedisCommand { name: "LTRIM", syntax: "LTRIM key start stop", description: "Trim a list to the specified range", group: "list" },
    RedisCommand { name: "RPOPLPUSH", syntax: "RPOPLPUSH source destination", description: "Remove the last element in a list, prepend it to another list and return it", group: "list" },
    RedisCommand { name: "LMOVE", syntax: "LMOVE source destination LEFT|RIGHT LEFT|RIGHT", description: "Pop an element from a list, push it to another list and return it", group: "list" },
    RedisCommand { name: "BLPOP", syntax: "BLPOP key [key ...] timeout", description: "Remove and get the first element in a list, or block until one is available", group: "list" },
    RedisCommand { name: "BRPOP", syntax: "BRPOP key [key ...] timeout", description: "Remove and get the last element in a list, or block until one is available", group: "list" },
    RedisCommand { name: "SPOP", syntax: "SPOP key [count]", description: "Remove and return one or multiple random members from a set", group: "set" },
    RedisCommand { name: "SRANDMEMBER", syntax: "SRANDMEMBER key [count]", description: "Get one or multiple random members from a set", group: "set" },
    RedisCommand { name: "SMOVE", syntax: "SMOVE source destination member", description: "Move a member from one set to another", group: "set" },
    RedisCommand { name: "SUNION", syntax: "SUNION key [key ...]", description: "Add multiple sets", group: "set" },
    RedisCommand { name: "SINTER", syntax: "SINTER key [key ...]", description: "Intersect multiple sets", group: "set" },
    RedisCommand { name: "SDIFF", syntax: "SDIFF key [key ...]", description: "Subtract multiple sets", group: "set" },
    RedisCommand { name: "ZRANK", syntax: "ZRANK key member", description: "Determine the index of a member in a sorted set", group: "sorted_set" },
    RedisCommand { name: "ZREVRANK", syntax: "ZREVRANK key member", description: "Determine the index of a member in a sorted set, with scores ordered high to low", group: "sorted_set" },
    RedisCommand { name: "ZINCRBY", syntax: "ZINCRBY key increment member", description: "Increment the score of a member in a sorted set", group: "sorted_set" },
    RedisCommand { name: "ZREVRANGE", syntax: "ZREVRANGE key start stop [WITHSCORES]", description: "Return a range of members in a sorted set, by index, with scores ordered from high to low", group: "sorted_set" },
    RedisCommand { name: "ZRANGEBYSCORE", syntax: "ZRANGEBYSCORE key min max [WITHSCORES] [LIMIT offset count]", description: "Return a range of members in a sorted set, by score", group: "sorted_set" },
    RedisCommand { name: "ZCOUNT", syntax: "ZCOUNT key min max", description: "Count the members in a sorted set with scores within the given values", group: "sorted_set" },
    RedisCommand { name: "JSON.GET", syntax: "JSON.GET key [path]", description: "Get JSON value at path", group: "json" },
    RedisCommand { name: "JSON.SET", syntax: "JSON.SET key path value", description: "Set JSON value at path", group: "json" },
    RedisCommand { name: "JSON.MERGE", syntax: "JSON.MERGE key path value", description: "Merge JSON value at path", group: "json" },
    RedisCommand { name: "JSON.DEL", syntax: "JSON.DEL key [path]", description: "Delete JSON value at path", group: "json" },
    RedisCommand { name: "JSON.TYPE", syntax: "JSON.TYPE key [path]", description: "Get the type of JSON value at path", group: "json" },
    RedisCommand { name: "JSON.OBJKEYS", syntax: "JSON.OBJKEYS key [path]", description: "Return the keys of a JSON object at path", group: "json" },
    RedisCommand { name: "JSON.ARRLEN", syntax: "JSON.ARRLEN key [path]", description: "Return the length of a JSON array at path", group: "json" },
    RedisCommand { name: "MEMORY", syntax: "MEMORY subcommand [arguments]", description: "A container for memory diagnostics commands", group: "server" },
    RedisCommand { name: "TIME", syntax: "TIME", description: "Return the current server time", group: "server" },
    RedisCommand { name: "MONITOR", syntax: "MONITOR", description: "Listen for all requests received by the server in real time", group: "server" },
    RedisCommand { name: "COMMAND", syntax: "COMMAND [subcommand]", description: "Get array of Redis command details", group: "server" },
    RedisCommand { name: "PUBLISH", syntax: "PUBLISH channel message", description: "Post a message to a channel", group: "pubsub" },
    RedisCommand { name: "SUBSCRIBE", syntax: "SUBSCRIBE channel [channel ...]", description: "Listen for messages published to the given channels", group: "pubsub" },
    RedisCommand { name: "UNSUBSCRIBE", syntax: "UNSUBSCRIBE [channel [channel ...]]", description: "Stop listening for messages posted to the given channels", group: "pubsub" },
    RedisCommand { name: "PSUBSCRIBE", syntax: "PSUBSCRIBE pattern [pattern ...]", description: "Listen for messages published to channels matching the given patterns", group: "pubsub" },
    RedisCommand { name: "PUBSUB", syntax: "PUBSUB subcommand [argument [argument ...]]", description: "Inspect the state of the Pub/Sub subsystem", group: "pubsub" },
    RedisCommand { name: "EVAL", syntax: "EVAL script numkeys key [key ...] arg [arg ...]", description: "Execute a Lua script server side", group: "scripting" },
    RedisCommand { name: "EVALSHA", syntax: "EVALSHA sha1 numkeys key [key ...] arg [arg ...]", description: "Execute a Lua script server side", group: "scripting" },
    RedisCommand { name: "SCRIPT", syntax: "SCRIPT subcommand [argument]", description: "Manage the script cache", group: "scripting" },
    RedisCommand { name: "UNLINK", syntax: "UNLINK key [key ...]", description: "Delete a key asynchronously in another thread", group: "generic" },
    RedisCommand { name: "COPY", syntax: "COPY source destination [DB destination-db] [REPLACE]", description: "Copy the value of a key", group: "generic" },
    RedisCommand { name: "MOVE", syntax: "MOVE key db", description: "Move a key to another database", group: "generic" },
    RedisCommand { name: "OBJECT", syntax: "OBJECT subcommand [arguments]", description: "Inspect the internals of Redis objects", group: "generic" },
    RedisCommand { name: "DUMP", syntax: "DUMP key", description: "Return a serialized version of the value stored at the specified key", group: "generic" },
    RedisCommand { name: "RESTORE", syntax: "RESTORE key ttl serialized-value [REPLACE] [ABSTTL] [IDLETIME seconds] [FREQ frequency]", description: "Create a key using the provided serialized value", group: "generic" },
    RedisCommand { name: "BITCOUNT", syntax: "BITCOUNT key [start end]", description: "Count set bits in a string", group: "bitmap" },
    RedisCommand { name: "BITOP", syntax: "BITOP operation destkey key [key ...]", description: "Perform bitwise operations between strings", group: "bitmap" },
    RedisCommand { name: "BITPOS", syntax: "BITPOS key bit [start [end]]", description: "Find first bit set or clear in a string", group: "bitmap" },
    RedisCommand { name: "SETBIT", syntax: "SETBIT key offset value", description: "Sets or clears the bit at offset in the string value stored at key", group: "bitmap" },
    RedisCommand { name: "GETBIT", syntax: "GETBIT key offset", description: "Returns the bit value at offset in the string value stored at key", group: "bitmap" },
    RedisCommand { name: "PFADD", syntax: "PFADD key element [element ...]", description: "Adds the specified elements to the specified HyperLogLog", group: "hyperloglog" },
    RedisCommand { name: "PFCOUNT", syntax: "PFCOUNT key [key ...]", description: "Return the approximated cardinality of the set(s) observed by the HyperLogLog at key(s)", group: "hyperloglog" },
    RedisCommand { name: "PFMERGE", syntax: "PFMERGE destkey sourcekey [sourcekey ...]", description: "Merge N different HyperLogLogs into a single one", group: "hyperloglog" },
    RedisCommand { name: "GEOADD", syntax: "GEOADD key longitude latitude member [longitude latitude member ...]", description: "Add one or more geospatial items in the geospatial index represented using a sorted set", group: "geo" },
    RedisCommand { name: "GEOHASH", syntax: "GEOHASH key member [member ...]", description: "Return members of a geospatial index as standard geohash strings", group: "geo" },
    RedisCommand { name: "GEOPOS", syntax: "GEOPOS key member [member ...]", description: "Return longitude, latitude of member", group: "geo" },
    RedisCommand { name: "GEODIST", syntax: "GEODIST key member1 member2 [unit]", description: "Return the distance between two members in the geospatial index", group: "geo" },
    RedisCommand { name: "GEORADIUS", syntax: "GEORADIUS key longitude latitude radius unit [WITHCOORD] [WITHDIST] [WITHHASH] [COUNT count] [ASC|DESC] [STORE key] [STOREDIST key]", description: "Query a sorted set representing a geospatial index", group: "geo" },
];

pub fn find_commands(prefix: &str) -> Vec<&'static RedisCommand> {
    let upper = prefix.to_uppercase();
    REDIS_COMMANDS
        .iter()
        .filter(|cmd| cmd.name.starts_with(&upper))
        .take(10)
        .collect()
}

pub fn find_command(name: &str) -> Option<&'static RedisCommand> {
    let upper = name.to_uppercase();
    REDIS_COMMANDS.iter().find(|cmd| cmd.name == upper)
}
